apiVersion: v1
kind: Secret
metadata:  
  name: userinfo-secrets
type: Opaque
data:
  mongo_uri: bW9uZ29kYitzcnY6Ly9tb2hhbWVkOjEyM0BjbHVzdGVyMC5keXRqZi5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5