apiVersion: apps/v1
kind: Deployment
metadata:
  name: userinfo-deployment
  labels:
    app: userinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userinfo
  template:
    metadata:
      labels:
        app: userinfo
    spec:
      containers:
      - name: userinfo
        image: streamio.azurecr.io/streamio-backend_userinfo:latest
        env:
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: userinfo-secrets
                key: mongo_uri
          - name: PORT
            value: "4002"
        ports:
        - containerPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: userinfo-service
spec:
  selector:
    app: userinfo
  ports:
    - port: 4002
      targetPort: 4002